### ISSUE TITLE
[BUG] PHP 8.1 Undefined array key

### ISSUE THREAD

**Issue by bh-teufels** [lochmueller/sourceopt#102]
problems with the use of sourceopt under
Typo3 11.5.16
PHP 8.1
sourceopt: 4.0.5

Errors:
```
PHP Warning: Undefined array key "svgstore." in /app/web/typo3conf/ext/sourceopt/Classes/Middleware/SvgStoreMiddleware.php line 30
PHP Warning: Undefined array key "formatHtml." in /app/web/typo3conf/ext/sourceopt/Classes/Service/CleanHtmlService.php line 72
```

Fix: check isset before use

**Comment by xerc** [comment]
@lochmueller there are many more locations (to check) ; whats your proposition ?

**Comment by lochmueller** [comment]
Hey @xerc & @bh-teufels 
I suggest adding the "Null coalescing operator" to all locations with this problem.
Regards,
Tim

**Comment by xerc** [comment]
there is already one but on the "first level";
https://github.com/lochmueller/sourceopt/blob/06819d3cea844261b9c346604881d754c991f873/Classes/Middleware/SvgStoreMiddleware.php#L30
& checking every `constant` would be slow

**Comment by lochmueller** [comment]
Hey @xerc 

I think this would not effect the performance or would be much slower.
If there are many places... I suggest to create a TypoScriptFrontendControllerConfiguration Object, that handle the access to "$GLOBALS['TSFE']->config['config']" and take care of valid paths. Then there is only one place, that access "$GLOBALS['TSFE']->config['config']"...

What do you think?

Regards,
Tim

**Comment by xerc** [comment]
good idea // until then this should FIX the issue

**Comment by lochmueller** [comment]
OK... then let's close the issue. We can still rework some classes in the extension :) Will publish a 5.0.0 release in a few minutes.
