### ISSUE TITLE
PHP Runtime Deprecation Notice if svgstore is enabled

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/sourceopt#105]
If i enable svgstore (`svgstore.enabled = 1`) this exception pops up:

`PHP Runtime Deprecation Notice: Automatic conversion of false to array is deprecated in /Users/***/typo3conf/ext/sourceopt/Classes/Service/SvgStoreService.php line 158`

TYPO3 11.5.16
sourceopt 4.0.5

**Comment by xerc** [comment]
https://github.com/lochmueller/sourceopt/blob/06819d3cea844261b9c346604881d754c991f873/Classes/Service/SvgStoreService.php#L155-L158

**Comment by xerc** [comment]
@bavarianbytes can not re-create this notice @ TYPO3 11.5.16 / PHP 8.1.7 ; did you try `dev-master`?

**Comment by lochmueller** [comment]
I also don't saw the error... but I suggest to avoid assignments in conditions. Perhaps we should avoid the double assignment in this condition to increase the readability of the code?!

**Comment by lochmueller** [comment]
@bavarianbytes Please check again current master. If the problem is still there, please send us a note...

**Comment by bavarianbytes** [comment]
Thanks, tried the current master. The exception is caused by line 162 now:
`$this->svgFileArr[$file['path']] = $file['defs'];`

Full Exception:
```
at TYPO3\CMS\Core\Error\ErrorHandler->handleError(8192, 'Automatic conversion of false to array is deprecated', '/Users/***/typo3conf/ext/sourceopt/Classes/Service/SvgStoreService.php', 162)
in /Users/***/typo3conf/ext/sourceopt/Classes/Service/SvgStoreService.php line 162
            $file['path'] = '/'.$storageArr[$file['storage']].$file['identifier']; // ^[/]
            $file['defs'] = $this->addFileToSpriteArr($file['sha1'], $file['path']);

            if (null !== $file['defs']) {
                $this->svgFileArr[$file['path']] = $file['defs'];
            }
        }
        unset($storageArr, $storage, $fileArr, $file); // save MEM
```

**Comment by xerc** [comment]
please add a `var_dump($file);` in line [160] and past the output here - thx

**Comment by bavarianbytes** [comment]
> var_dump($file);

```
array(5) { ["storage"]=> int(1) ["identifier"]=> string(27) "/demo/logos/basic_ipsum.svg" ["sha1"]=> string(40) "05cef80e9b3ba6573a0a9d7ee11388caedf5e03e" ["path"]=> string(37) "/fileadmin/demo/logos/basic_ipsum.svg" ["defs"]=> array(2) { ["attr"]=> string(22) "viewBox="0 0 1998 434"" ["hash"]=> string(40) "05cef80e9b3ba6573a0a9d7ee11388caedf5e03e" } }
```

**Comment by xerc** [comment]
found it ; FIX @ https://github.com/lochmueller/sourceopt/pull/107

**Comment by bavarianbytes** [comment]
Works! Thank you!

**Comment by xerc** [comment]
aber gern  :smile:
