### ISSUE TITLE
Bug in JSON-Escaping

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/sourceopt#110]
Lets say you have this JSON script tag on your page:
```
<script id="om-cookie-consent" type="application/json">
{
    "cookie-32": {
        "header": ["<script>\r\n  ...<\/script>\r\n<noscript><img height=\"1\" width=\"1\" style=\"display:none\" src=\"https:\/\/www.facebook.com\/tr?id=...\" \/><\/noscript>"]
    }
}
</script>
```

The slash of the closing img tag is JSON escaped: `<img ... \/>`

If sourceopt is activated it makes this out if it and breaks it: `<img ... \>`

**Comment by xerc** [comment]
https://github.com/lochmueller/sourceopt/blob/961fd38a28ae84958a069044e25d48a3aba99672/Classes/Service/CleanHtmlService.php#L126-L134

**Comment by xerc** [comment]
@bavarianbytes this is a bit triky
@lochmueller `[^>]` => `[^>\\\\]` ?

**Comment by lochmueller** [comment]
@bavarianbytes please check this match:
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L170

The script block should not touch by EXT:sourceopt in general. I think there is the problem....

Regards
Tim

**Comment by xerc** [comment]
@bavarianbytes please check `dev-master`

**Comment by lochmueller** [comment]
I will close this issue. Please check current master. If the problem still exists, feel free to add some unit tests.
