### ISSUE TITLE
PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/sourceopt#114]
`PHP Runtime Deprecation Notice: Creation of dynamic property HTML\Sourceopt\Service\SvgStoreService::$svgs is deprecated in /Users/***/typo3conf/ext/sourceopt/Classes/Service/SvgStoreService.php line 27`

Seems like `$this->svgs = [];` is causing it.

PHP 8.2
sourecopt 5.0.0
TYPO3 11.5.19

**Comment by xerc** [comment]
thx for the info ; ref. https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by lochmueller** [comment]
@xerc [AllowDynamicProperties] is not really a good solution (don't know that a attribute allow this madness ;)). We should define the properties that are used in the classes to avoid for example type conflicts and support auto complete in IDE.

**Comment by xerc** [comment]
@bavarianbytes may you please test the second PATCH ?

**Comment by bavarianbytes** [comment]
> @bavarianbytes may you please test the second PATCH ?

Sorry, didn't got message that you provided a fix. Tested it now.
You forgot to define `$svgFileArr`. After adding that, it works!
