### ISSUE TITLE
Idea/feature request: cache SVGs with gradients

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/sourceopt#117]
Seems like SVGs are not stored as symbols if there is a `<linearGradient>` in the SVG file. `SvgStoreService.php` skips the file if `url` is found (<`linearGradient>`s are used to fill shapes via `fill="url(#myGradientId)"`).

A solution seems to be to place `<linearGradient>`s in a `<defs>` part outside of  the `<symbol>`: https://stackoverflow.com/questions/52439187/linear-gradient-in-svg-symbol/52443861#52443861

**Comment by xerc** [comment]
there are?/whare issues with gradients ; try by de-commenting ..
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/SvgStoreService.php#L138-L152
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/SvgStoreService.php#L218
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/SvgStoreService.php#L224 (opt.)

and change `/<(?:style|defs)|url\(/` to `/<style/`
@ https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/SvgStoreService.php#L131

**Comment by bavarianbytes** [comment]
Thx, i'll try.

**Comment by xerc** [comment]
@bavarianbytes is browser support sufficient nowadays?

**Comment by bavarianbytes** [comment]
Browser support looks good: https://caniuse.com/?search=lineargradient

**Comment by xerc** [comment]
Chrome & Safari are still buggy ; https://xerc.de/test.htm

**Comment by bavarianbytes** [comment]
Ok, caniuse didn't told that. Then maybe wait till support is sufficient.
