### ISSUE TITLE
HTML\Sourceopt\Service\CleanHtmlService::formatHtml(): Argument #1 ($html) must be of type string, null given

### ISSUE THREAD

**Issue by velletti** [lochmueller/sourceopt#118]
PHP: 8.1.17
TYPO3: 11.5.25
Sourceopt: 5.0

in some Cases during POST Requests (search request in f.e. kesearch, filling forms ad submit) "html" is null
so i get this TypeError (in v4 : wrong argument for preg_match_all() ) 

```
HTML\Sourceopt\Service\CleanHtmlService::formatHtml(): Argument #1 ($html) must be of type string, null given, 
called in /var/www/html/http/typo3conf/ext/sourceopt/Classes/Service/CleanHtmlService.php on line 132
```

called by: 

```
132: protected function formatHtml(string $html):string

 if ($this->formatType > 0) {
      $html = $this->formatHtml($html);
  }
```

reason unclear but if the preg_replace() in    // cleanup HTML5 self-closing elements 
runs into an error, it returns Null so the next formatHtml( null )  will run into error.

**Comment by xerc** [comment]
@velletti would you please do `var_dump` in line [130] to check whats insinde `$html` and may provide the `preg_replace` error
