### ISSUE TITLE
PHP warning: undefined array key "svgstore" in ../ ../SvgStoreMidddleeware.php.

### ISSUE THREAD

**Issue by ghost** [lochmueller/sourceopt#124]
typo3 version 11.5
php version 8.0.29.

When i install and active typo3 extension "sourceopt" then i get frontend error `PHP warning: undefined array key "svgstore" in ../ ../SvgStoreMidddleeware.php.`

**Comment by xerc** [comment]
did you include EXT [typoscript](https://github.com/lochmueller/sourceopt/tree/master/Configuration/TypoScript) ?

**Comment by lochmueller** [comment]
Hey @ghost,
could you add the extension version and the line of the error?
Regards,
Tim

**Comment by xerc** [comment]
@lochmueller ; deleted user

**Comment by lochmueller** [comment]
OK. I close this issue ;)
