### ISSUE TITLE
PHP Runtime Deprecation Notice: Creation of dynamic property HTML\Sourceopt\Service\SvgStoreService::$svgFileArr is deprecated in /.../lochmueller/sourceopt/Classes/Service/SvgStoreService.php line 71

### ISSUE THREAD

**Issue by mhuebe** [lochmueller/sourceopt#125]
TYPO3: 12.4
PHP: 8.2.7

When calling up the frontend, the following error message is displayed:

`PHP Runtime Deprecation Notice: Creation of dynamic property HTML\Sourceopt\Service\SvgStoreService::$svgFileArr is deprecated in /.../lochmueller/sourceopt/Classes/Service/SvgStoreService.php line 71`

**Comment by xerc** [comment]
FIX @ https://github.com/lochmueller/sourceopt/commit/54360460358b3a249e06a6bc49dd0a69891613e7

**Comment by xerc** [comment]
@lochmueller ; https://extensions.typo3.org/extension/sourceopt has only 5.0.0

**Comment by mhuebe** [comment]
@xerc I use the version `5.0.1` of the extension

**Comment by xerc** [comment]
this commit was not included => @lochmueller ; please create new release - THX

**Comment by lochmueller** [comment]
Done: https://github.com/lochmueller/sourceopt/releases/tag/5.0.2

**Comment by xerc** [comment]
if you have time please check https://github.com/lochmueller/sourceopt/commit/d4425c69b083e7f827b51985651c305c12f9d0f1/checks/14794433930/logs/8

**Comment by lochmueller** [comment]
Hey @xerc I will try in the next days. TER has no high prio for me anymore.
Regards,
Tim

**Comment by mhuebe** [comment]
Thanks to @xerc and @lochmueller. It works.
