### ISSUE TITLE
if "pathType" is not defined, a PHP warning is thrown

### ISSUE THREAD

**Issue by s-nunez** [lochmueller/sourceopt#140]
In this line: https://github.com/lochmueller/sourceopt/blob/6663a8a8512ba280bc7e8b8d38610146495a94ce/Classes/Service/SvgStoreService.php#L196

would it be possible to change it to?:
`            if (!empty($storage->getConfiguration()['pathType']) && 'relative' == $storage->getConfiguration()['pathType']) {
`

Thank you very much!

**Comment by xerc** [comment]
please provide dump(s) of `$storage->getConfiguration()`

**Comment by s-nunez** [comment]
In my case it is empty. It works for fileadmin fine but I use a custom storage to connect TYPO3 with AdmiralCloud (which it is a sort of S3 file storage).

I use this package https://github.com/CPS-IT/admiral-cloud-connector/tree/master

That is the reason, for this connector I don't need an extra configuration.

**Comment by xerc** [comment]
please provide `SELECT id,configuration FROM sys_file_storage` (and replace credentials with ###)

**Comment by s-nunez** [comment]
I followed the description here  https://github.com/CPS-IT/admiral-cloud-connector/tree/master and I did:

`
INSERT INTO `sys_file_storage` (`pid`, `cruser_id`, `deleted`, `description`, `name`, `driver`, `configuration`, `is_default`, `is_browsable`, `is_public`, `is_writable`, `is_online`, `auto_extract_metadata`, `processingfolder`) VALUES
    (0, 0, 0, 'Automatically created during the installation of EXT:admiral_cloud_connector', 'AdmiralCloud', 'AdmiralCloud', '', 0, 1, 1, 0, 1, 1, '1:/_processed_/');
`

As you can see, the column "configuration" is an empty string.

You can just execute this insert and you will get the PHP warning.

**Comment by xerc** [comment]
can you confirm ? https://github.com/lochmueller/sourceopt/commit/86e616d8de753d7bbbaf10186c1598e0cd0e2b6f

**Comment by s-nunez** [comment]
Thank you very much for your time! In my case, it would work as you propose. But I am now thinking a bit forward, if some configuration is set, $storageConfig would not be empty and a PHP warning would be thrown again. What do you think if instead of !empty($storageConfig) you use
```
if(isset($storageConfig['pathType'], $storageConfig['basePath']) && 'relative' == $storageConfig['pathType']) {

$storageArr[$storage->getUid()] = rtrim($storageConfig['basePath'], '/'); // [^/]$

}
```

Thank you very much again for your effort and your great extension.

**Comment by xerc** [comment]
nu? https://github.com/lochmueller/sourceopt/commit/531ecfb

**Comment by s-nunez** [comment]
That looks amazing to me!!! thank you very much!!!

**Comment by lochmueller** [comment]
Merged. I will close this issue....
