### ISSUE TITLE
Check Tests & release new version

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/sourceopt#145]
https://github.com/lochmueller/sourceopt/actions/runs/11332973047

**Comment by xerc** [comment]
https://github.com/lochmueller/sourceopt/pull/146/commits/dde145f3a180f54a604b78dbfaf567bfaf381d7b

**Comment by lochmueller** [comment]
Done. Fixed the bug in the test data provider and release a new version: https://github.com/lochmueller/sourceopt/releases/tag/5.2.0
