### ISSUE TITLE
Fatal Error in Frontend in TYPO3 13.4.0

### ISSUE THREAD

**Issue by wowaTYPO3** [lochmueller/sourceopt#147]
I have installed the current version of the extension in TYPO3 13.4.0, setup and constants are imported.

I get the following error message in the frontend:

`Fatal error: Non-readonly class HTML\Sourceopt\Resource\SvgFileRepository cannot extend readonly class TYPO3\CMS\Core\Resource\FileRepository in /var/www/html/vendor/lochmueller/sourceopt/Classes/Resource/SvgFileRepository.php on line 0`

No stacktrace, only this error, despite activated debug mode.
Unfortunately, I have no idea what to do here.

**Comment by wowaTYPO3** [comment]
Oh sorry, PHP 8.3.10 on a local Docker/DDEV environment.

**Comment by cbaur** [comment]
I can confirm this error (probably got the same setup with DDEV / TYPO3 13.4.0 / PHP 8.3.10).

@xerc I also tried your fix from #148 and while that indeed solves this error, I found that there need to some further modifications to be made in this class in lines 51 and 52

```php
$queryBuilder
....

->execute()
->fetchAll();
```

Both these methods had been deprecated in T3 12 and removed in 13 (see [here](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96287-DoctrineDBALv3.html#migration) and [there](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-96972-DeprecateQueryBuilderexecute.html))

Following the migration guides, I changed these lines to

```php
->executeQuery()
->fetchAllAssociative() 
```

and everything worked as expected.

However, this change will of course impact the extension's compatibility to older TYPO3 versions without doctrine/dbal. Maybe support for these should be dropped?

**Comment by lochmueller** [comment]
I published a new release https://github.com/lochmueller/sourceopt/releases/tag/5.2.1 incl. the PR/fix. I also prepare a release that drop the old PHP/TYPO3 versions to get a more modern codebase: https://github.com/lochmueller/sourceopt/commit/bee92015241f033771620eff3ce9a743487f6519
If there are open points for the next v12/v13 only release, feel free to send pull requests.

**Comment by xerc** [comment]
@lochmueller please check comments at ..
https://github.com/lochmueller/sourceopt/commit/5cc52f34fda4bdb64d67d2cb30adbc707115fa26#r148429409
https://github.com/lochmueller/sourceopt/commit/5cc52f34fda4bdb64d67d2cb30adbc707115fa26#r148429348

btw/ do you like <space> per/post <dot> concatenation ?

**Comment by lochmueller** [comment]
Hey @xerc 
I checked the comments and reply to yours. Related to "pre/post dot-concatenation spaces": I have no preference for that but I like strong standards. I switch to PER2.0 with the coding standard in PHP CS Fixer: https://www.php-fig.org/per/coding-style/ I do not touch things manually....
Regards,
Tim

**Comment by xerc** [comment]
@wowaTYPO3 @cbaur ; please test version `5.2.2` at your dev/test typo3 `^13.4` with special focus on SVG combination

**Comment by lochmueller** [comment]
I close this issue. If there are followups, please create new issues.
