### ISSUE TITLE
Documentation should include warning that huge html content is slow

### ISSUE THREAD

**Issue by lolli42** [lochmueller/sourceopt#15]
I was just looking at a site that had huge server side rendering times. It turned out that nearly 4 seconds were eaten by the main hook "cleanUncachedContent" handling a 130kB HTML source file. With disabling the extension parse time dropped to 150 milliseconds.

Imho, the documentation should at least contain a big fat warning that parsing is very slow for parsing "bigger" HTML content.

**Comment by lochmueller** [comment]
I will add a notice to the documentation in my next sprint for my community extension.

Thank you for the tip...
