### ISSUE TITLE
No HTML cleaning with latest version

### ISSUE THREAD

**Issue by fiedomedia** [lochmueller/sourceopt#151]
At the moment no html cleaning is done because a check in the middleware fails. It looks like a bug in the latest release.

There is a condition for $this->responseIsAlterable($response):
https://github.com/lochmueller/sourceopt/blob/20ad2d5b70f936752fd9875423068c2d880b0906/Classes/Middleware/CleanHtmlMiddleware.php#L23

But this always returns false because of this line:
https://github.com/lochmueller/sourceopt/blob/20ad2d5b70f936752fd9875423068c2d880b0906/Classes/Middleware/AbstractMiddleware.php#L18

If $response IS instanceof NullResponse then it should return false.

Tested with sourceopt 5.2.2 in latest TYPO3 12 with PHP 8.2

**Comment by lochmueller** [comment]
Hey @fiedomedia 
you are right. Fixed in current main branch. Release will follow...

Regards,
Tim
