### ISSUE TITLE
PHP Warning: Undefined array key "replacer." in vendor/lochmueller/sourceopt/Classes/Middleware/RegExRepMiddleware.php line 23

### ISSUE THREAD

**Issue by siwa-pparzer** [lochmueller/sourceopt#152]
you need to put `$GLOBALS['TSFE']->config['config']['replacer.'] ?? false` into `( )` to work correctly

bug was introduced in version 5.2.2
in 5.2.1 it was correctly between `( )`

**Comment by bh-teufels** [comment]
getting same error 

TYPO3 12.4.22
PHP 8.3
soruceopt 5.2.3

**Comment by lochmueller** [comment]
Merged. Release will follow in a few minutes.
