### ISSUE TITLE
Error in CleanHtmlService.php

### ISSUE THREAD

**Issue by maximaexchen** [lochmueller/sourceopt#24]
I can not reproduce, but sometimes I have this error in my administrationprotocol.

Core: Error handler (FE): PHP Warning: preg_match(): Empty regular expression in /var/www/httpdocs/typo3conf/ext/sourceopt/Classes/Service/CleanHtmlService.php line 525

Should not be possible due to (!empty), but...

**Comment by lochmueller** [comment]
1.0.0 released a few seconds ago. I think perhaps the error is gone. If the error still exists... please rereport the issue... 

Regards,
Tim

**Comment by maximaexchen** [comment]
Sorry for late reply.
Thanks for info. 
Unfortunately this project still is and will run with 6.2.
Cannot update to 1.0.0
Do you have a hint how I catch the error in the 

`foreach ($this->whiteListCommentsPatterns as $pattern)`

**Comment by lochmueller** [comment]
Just check the regex variable in front of the preg_match call.
