### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cedricziel** [lochmueller/sourceopt#25]
The extension can't currently be required with composer, since 1218f591c2188831b9f674de4d9b32a28e842cc8 is not part of any tag. Could you release a patch version so we can switch from dev-master to a tag again?

**Comment by lochmueller** [comment]
Done. :)

`composer require lochmueller/sourceopt` will install version 1.0.0 now.

**Comment by cedricziel** [comment]
Great! Thx a bunch! :+1:
