### ISSUE TITLE
[BUG] json Data

### ISSUE THREAD

**Issue by grimmcreative** [lochmueller/sourceopt#26]
With sourceopt running - json Data gets invalid.

**Comment by lochmueller** [comment]
Hey @grimmcreative 

pelase add a test-case incl. the wrong and the expected result.

Regards,
Tim

**Comment by grimmcreative** [comment]
testsetup - all ok - no sourceopt
just click to last step of form - json data is correct
https://dev.sogenial.eu/testsetup/index.php?id=53

mainsetup - sourceopt active - json data not ok
https://dev.sogenial.eu/index.php?id=2

**Comment by lochmueller** [comment]
I close this issue. Please diable source opt handling in json mode.
