### ISSUE TITLE
Line-breaks get removed in the value-attribute of input fields

### ISSUE THREAD

**Issue by rr-it** [lochmueller/sourceopt#27]
Multi-line content in the `value`-attribute of `input`-tags is converted to single line.
E.g. powermail uses hidden input fields to pass along multi-line content of textarea-inputs.

Is it possible to keep line-breaks untouched in the `value`-attribute of `input`-tags?

**Comment by lochmueller** [comment]
Puuuhhh... It's long ago all the regex stuff ;) I will check this in the next days/weeks..
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L453

**Comment by rr-it** [comment]
I looked into the `function removeNewLines()`
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L453
For me it looks like there are no calls to this `function removeNewLines()`.

The `input`-tags get cleaned in the `function formatHtml()` by calling the `function killLineBreaks()`
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L281

I'll give it a try to fix it. Please have a look at

**Comment by rr-it** [comment]
I looked into the `function removeNewLines()`. For me it looks like there are no calls to this `function removeNewLines()`.
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L453

The `input`-tags get cleaned in the `function formatHtml()` by calling the `function killLineBreaks()`
https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L281


I gave it a try to fix it. Please have a look at
https://gist.github.com/rr-it/03869b8a3a5c804e12aadc9aa46dce02
(diff: https://gist.github.com/rr-it/ab6a02a8b0d979b69d7ec687081a2c4e)


Instead of calling `function killLineBreaks()` it is calling `function removeNewLines()` now. The `function removeNewLines()` calls `function removeNewLines()` if necessary.
https://gist.github.com/rr-it/03869b8a3a5c804e12aadc9aa46dce02#file-cleanhtmlservice-php-L282

The `function removeNewLines()` is totally changed
https://gist.github.com/rr-it/03869b8a3a5c804e12aadc9aa46dce02#file-cleanhtmlservice-php-L455

First I did some restructuring - this hopefully did not change any programmatic logics.
https://gist.github.com/rr-it/f909a7c78bf38825f64ab5d914ee6e5a

With the new structure in place, I extended the function to recognize the `value`-attribute of `input`-tags. Then, if necessary, the `function removeNewLines()` gets called.

**Comment by lochmueller** [comment]
I close this issue... I suggest a Middleware solution instead of EXT:sourceopt.
