### ISSUE TITLE
Remove optional tags in HTML5

### ISSUE THREAD

**Issue by vergissberlin** [lochmueller/sourceopt#28]
**Hi,**

did you know with HTML5, a lot of tags are optional. Take a look at [Google Style Guide](https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags) and the [HTML5 specification](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission). With that technique we are able to save a lot of bytes.
It would  be nice if *sourceopt* can handle this.

kind regards,
André

**Comment by vergissberlin** [comment]
# Examples
## Not recommended
```
<!DOCTYPE html>
<html>
  <head>
    <title>Spending money, spending bytes</title>
  </head>
  <body>
    <p>Sic.</p>
  </body>
</html>
```
## Recommended
```
<!DOCTYPE html>
<title>Saving money, saving bytes</title>
<p>Qed.

**Comment by lochmueller** [comment]
@vergissberlin I do not know, that this is possible. Do you know a stable lib for that?

**Comment by vergissberlin** [comment]
For PHP currently unfortunately not.  https://www.npmjs.com/package/express-minify-html can do that very well. It is based on https://github.com/kangax/html-minifier/. I am looking forward to finding a library.

**Comment by lochmueller** [comment]
No... not yet. I will check this in my next community sprint...

**Comment by Gitsko** [comment]
Is there a new status or new findings on this topic?

**Comment by lochmueller** [comment]
No. There are no new news. It is hard to integrate by myself. So the next sourceopt version (composer only) will based on something like https://github.com/ArjanSchouten/HtmlMinifier

**Comment by lochmueller** [comment]
I close this issue. Next version will be based on external libs for format processing
