### ISSUE TITLE
sourceopt.formatHtml = 4 leaves spaces between HTML tags

### ISSUE THREAD

**Issue by magicsunday** [lochmueller/sourceopt#30]
Not all spaces between HTML tags are removed, some are left over.

**Comment by lochmueller** [comment]
@magicsunday Could you add some code examples?

**Comment by magicsunday** [comment]
Add the following on top of the `formatHtml` method:

```
$html = <<<HTML
<a href="TEST">Blah</a>

<div>
    TEST
    <div class="test">test</div>
</div>
<div>test1</div>  <div>test2</div>
<div>test3</div> <div>test4</div>
HTML;

echo "<pre>" . print_r(htmlspecialchars($html), true) . "</pre>";
```

The output is the following:

`<a href="TEST">Blah</a> <div> TEST <div class="test">test</div> </div> <div>test1</div> <div>test2</div> <div>test3</div> <div>test4</div>`

Note the white space between the tags and after "TEST" in the first `<div>`.

**Comment by lochmueller** [comment]
Could be dropped with the new settings of this commit:
https://github.com/lochmueller/sourceopt/commit/b2f025c352f50e24bd1f80c22f79105e482099bb

Regards,
Tim

**Comment by magicsunday** [comment]
When did you plan to release this fix?

**Comment by lochmueller** [comment]
I don't know... in the next days/weeks.... If it is urgent you could switch to dev-master.
