### ISSUE TITLE
[BUG] new line inside tag replacement - no white space kept

### ISSUE THREAD

**Issue by AndreasA** [lochmueller/sourceopt#31]
Hi,

if I have something like this:
```
<div>foo
bar</div>
````
With no whitespace between "foo" and "bar" except one new line. Then that whitespace gets completely lost and in the end the display will be "foobar" instead.
Most likely there will be a whitespace somewhere after or before a line break, so it will very likely not be an issue but it should still be fixed.

Tried with formatHtml = 1 and formatHtml = 4

**Comment by lochmueller** [comment]
Hey @AndreasA 
thanks for reporting. I will switch to an HTML minifier Lib shortly, so I do not maintain alls this small problems anymore...
Regards,
Tim

**Comment by AndreasA** [comment]
Ah. OK. Have you considered also adding an option for compressJS / compressCSS (by using the corresponding PageRenderer hook, e.g. jsCompressHandler ) because the default TYPO3 compressJS option doesn't do much except gzip the JS.
Of course, in the best case one has an own frontend workflow for compression of JS / CSS files but it would be a nice option - there should be existing third party libraries for this.

**Comment by lochmueller** [comment]
Also a good idea. Perhaps you create new issues for other features/ideas...
