### ISSUE TITLE
[FEATURE] add javascript / css minifier option

### ISSUE THREAD

**Issue by AndreasA** [lochmueller/sourceopt#32]
TYPO3 by default does only a very simplistic javascript / css compression when activiating the corresponding compressJS / compressCSS options.
It would be nice to optionally add some existing third party libraries for this and use:
`$GLOBALS['TYPO3_CONF_VARS'][TYPO3_MODE]['jsCompressHandler']`
and
`$GLOBALS['TYPO3_CONF_VARS'][TYPO3_MODE]['cssCompressHandler']`

Warning: If this one is overriden, it might also be necessary to fix some "paths" in the CSS files (if it is excluded from concatination), see method \TYPO3\CMS\Core\Resource\ResourceCompressor::compressCssFile
especially:
```
if (!file_exists((PATH_site . $targetFile)) || $this->createGzipped && !file_exists((PATH_site . $targetFile . '.gzip'))) {
            $contents = $this->compressCssString(GeneralUtility::getUrl($filenameAbsolute));
            if (strpos($filename, $this->targetDirectory) === false) {
                $contents = $this->cssFixRelativeUrlPaths($contents, PathUtility::dirname($filename) . '/');
            }
            $this->writeFileAndCompressed($targetFile, $contents);
        }
```

Of course, the best option is probably to use a corresponding FE workflow but it would still be nice to have the option to compress those files without building a FE workflow.

**Comment by lochmueller** [comment]
Thanks for the feature request. sourceopt format only HTML. For CSS/JS there are other extensions in TER and also better processes (npm building) to build frontend ressources...
