### ISSUE TITLE
PHP Warning: preg_match(): Empty regular expression

### ISSUE THREAD

**Issue by snifterme** [lochmueller/sourceopt#33]
Hi! This message keeps appearing in TYPO3 error log:
`Core: Error handler (FE): PHP Warning: preg_match(): Empty regular expression in /var/www/clients/client1/web1/dev32aug/typo3conf/ext/sourceopt/Classes/Manipulation/RemoveComments.php line 70`
Also - comment "This website is powered by TYPO3 - inspiring people to share!" isn't removed.
I'm using TYPO3 v7.6.22 and Sourceopt 1.0.0

Thank you.

**Comment by lochmueller** [comment]
The TypoScript is missing. This is the reason for the empty regex configuration....
Please include the static TypoScript.
