### ISSUE TITLE
SVG and self-closing tags break indentation

### ISSUE THREAD

**Issue by rowild** [lochmueller/sourceopt#38]
Is seems sourceopt cannot deal with svg tags (that is also path, group, etc) or maybe even with self-closing tags (path is always self-closing, e.g.). 
When using `formatHtml = 4`, the source keeps indenting like this:

```
<path .../>
    <path .../>
        <path .../>
```

But is should be like this:
```
<path .../>
<path .../>
<path .../>
```

Even though formatHtml=4 seems like sugar on the cake and might everything but not recommended for real world scenarios, it would be nice to have it working properly, sind well-formated HTML is also a form of debugging. Things like double p-tags (which happens, if a f:format.html is wrapped inside a p-tag ... well, yes, it happens ...) would be easily recognizable.

Also, source formatting is a very weak topic in TYPO3 and only 2 ext (this one and "min") provide such a feature. And since TYPO3 is mainly a configuration monster, we need way more configuration than currently available!!! :-)
(seriously: Why not provide a "tag selector", so the user can define, what should be treated as block level element and what not - very much like phpstorm does)

Thank you!

**Comment by josefglatz** [comment]
@rowild beside the two mentioned extensions it's basically possible to implement any composer based library to compress the output via hook.

**Comment by lochmueller** [comment]
Hey both of you :) @josefglatz is right. If there is a next version of sourceopt it will be only a „wrapper“ between TYPO3 and a standalone lib for formatting source code (composer mode). This is much easier to maintain for me and much more flexible in the functionality. But at the moment the migration has no high priority on my task list ;) Regards, Tim

**Comment by rowild** [comment]
@josefglatz Just to clarify: I report bugs, because that's ne thing the community does. I added comments, because they refer to an email exchange that took place previously (because I do my research, before I post something). Probably I should have mentioned that.
However: A wrong formatting of SVG tags is not "my" issue, as you so eloquently put it...

**Comment by lochmueller** [comment]
I close this issue. The format lib will be replaced with a composer based external lib shortly.
