### ISSUE TITLE
New version for TYPO3 9.5 

### ISSUE THREAD

**Issue by Gitsko** [lochmueller/sourceopt#40]
Hi,

is a new version for TYPO3 9.5  planned? 

I see the master brach is compatible.

**Comment by lochmueller** [comment]
Hey @Gitsko 
There will be a new release in the next days/weeks.
I will try to switch to other "optimize" frameworks that the "sourceopt" extension is only a wrapper.
Regards,
Tim

**Comment by lochmueller** [comment]
The current master is replaced, so a middleware is used. I close this issue...
