### ISSUE TITLE
[BUG] Psr Middleware kills frontend

### ISSUE THREAD

**Issue by featdd** [lochmueller/sourceopt#43]
the changes in 94b7c32eecb5f228b932579a47a8022b70554d4f caused my frontend break.

I just got an empty response and no error -.-

**Comment by lochmueller** [comment]
Could you check if "$responseBody" is ok?

**Comment by featdd** [comment]
We found out that setting `config.sourceopt.enabled = 0` leads to a blank page

It was disabled by a context condition, if it was enabled it worked properly

**Comment by lochmueller** [comment]
Fixed by this patch: https://github.com/lochmueller/sourceopt/commit/e4eccc7b7712c8e3c3e2f15ce582edad421e5312
