### ISSUE TITLE
TYPO3 9.5.x TER

### ISSUE THREAD

**Issue by rafu1987** [lochmueller/sourceopt#46]
Hey there and thanks for your great extension.

When will you upload the newest version for TYPO3 9.5.x to the TER?

Thanks in advance :-)

**Comment by lochmueller** [comment]
Hey @rafu1987 

If the next release is finished I will push this also to TER.

There are still some tests and refactorings open. You could switch your composer.json to dev-master temporary, if you want to use the current master.

I will close this issue.

Regards,
Tim
