### ISSUE TITLE
Line-breaks are removed from ical Export

### ISSUE THREAD

**Issue by MichiSpandl** [lochmueller/sourceopt#47]
Hi,

I'm using TYPO3 9.5.7, sourceopt in the newest version, also tx_news in the newest version and we offer in the frontend ical files from tx_news for downloading. If I use sourceopt (tried formatHtml width config from 1-4) it removes the linebreaks from the ical files, and for this reason they are not working anymore. Is it possible to exclude some kind of special filetypes like ical?

Best regards and many thanks,
Michaela

**Comment by lochmueller** [comment]
Hey @MichiSpandl ,
sourceopt should only change the output of the FE rendering. There should by any parameter (type=xxx) or a special page for the ics output.
You could set config.sourceopt.enabled = 0 in this case, to disable the content manipultion.
Did that help?

Best regards,
Tim

**Comment by MichiSpandl** [comment]
*feeling stupid now...* 
yes sure that's the solution, thank you very much for your fast reply!

Best regards,
Michaela

**Comment by lochmueller** [comment]
Nice. So I will close this issue...
