### ISSUE TITLE
remove FLUID JumpMarks

### ISSUE THREAD

**Issue by xerc** [lochmueller/sourceopt#55]
`/(?:<a)?\sid="c[0-9]+"(?:><\/a>)?/g`

**Comment by lochmueller** [comment]
Hey @xerc ,
If you don't need this marker, I suggest to drop this line from your Template Layout. We should not use EXT:sourceopt for changeing the real markup, because the maipulations are not very efficient.
Regards,
Tim

**Comment by xerc** [comment]
how about `sourceopt.removeJumpMarks = 1` (default:0) via TypoScript Reference?

**Comment by lochmueller** [comment]
No. I think SourceOpt is not the right location to fix problems/functions in the templates. SourceOpt is for structual cleanups of the source code. Your example code is part of the FluidStyledContent rendering. So the best way is, to adapt the Template to solve this problem.
