### ISSUE TITLE
TER Version still requires TYPO3 9.5.99

### ISSUE THREAD

**Issue by rowild** [lochmueller/sourceopt#56]
I don't know if this version if going to TER, but there is a version 2.0, it just has different settings in the config like the one mentioned in the title.

Will that be changed?

**Comment by lochmueller** [comment]
Hey @rowild 
I close this issue. It is right... there is no release for TYPO3 v10 currently. Please use dev-master if you need TYPO3 v10 support.
Regards,
Tim

**Comment by rowild** [comment]
What a pity! 
Just to let you know: The extension file scanner reports only one minor issue, otherwise everything works fine.

Thanks for your quick response and clarification!

All the best! Robert

**Comment by lochmueller** [comment]
Yes... I know. But there is currently not enough time to test the current dev-master version. If there is time, I will release the next version...
