### ISSUE TITLE
[BUG] Split html into it's elements

### ISSUE THREAD

**Issue by ogrosko** [lochmueller/sourceopt#58]
Hello,
For some reason some pages returns this error: 

```
Oops, an error occurred!
PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/web/typo3conf/ext/sourceopt/Classes/Service/CleanHtmlService.php line 186
```
It looks like `preg_split` ([here](https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/CleanHtmlService.php#L189)) split html into it's elements doesn't returns array and it returns `FALSE`. This issue occures only on some pages.

**Comment by lochmueller** [comment]
Thanks for the note. Fixed in current master. 👍

**Comment by ogrosko** [comment]
Hi, byt this change  https://github.com/lochmueller/sourceopt/commit/e3e355f00f623de69cc5e8363658b9461f3e2dcc reconstruction of html fails. And `noFormat` parts are missing in final HTML
