### ISSUE TITLE
Classes/User/FrontendHook.php missing in latest *.t3x

### ISSUE THREAD

**Issue by vaxul** [lochmueller/sourceopt#6]
Hi,

today I have updated to the latest version from the TYPO3 repository in EM. I saw the change, that Classes/User/PageRendererHook.php was removed and wondered, why there is no new Hook to replace the old one.

To get sure, I redownload the *.t3x file from http://typo3.org/extensions/repository/view/sourceopt and installed it.

Again, no hook found in the folders and the extension doesn't work in the system.

I looked at this github repository and saw: sourceopt/Classes/User/FrontendHook.php. 

I downloaded and installed the latest master from github and now the extension work as expected.

It may be true that that this class is missing in the latest release in the TYPO3 repository?

Best regards

**Comment by lochmueller** [comment]
Hi,

I upload the current git master as 0.8.6 (incl. the missing class - double checked ;)) to TER. Please check the 0.8.6 update (available in a few minutes in TER) and send me same feedback if the class exists in this release...

Regards,
Tim

**Comment by vaxul** [comment]
Tested and now the class is included. =)
