### ISSUE TITLE
TYPO3 v10 compatibility

### ISSUE THREAD

**Issue by bmack** [lochmueller/sourceopt#60]
Hey,

are there any plans to do a v10 LTS compatible release (= tag)?

**Comment by lochmueller** [comment]
Hey @bmack 
I do not use the extension in production anymore and do not have feedback, if the current master works well in TYPO3 v10. I could just releasing the current master.... do you use the dev-master in production?
Regards,
Tim

**Comment by bmack** [comment]
Not yet in production, but we'll test dev-master and let you know, if everything works.

**Comment by lochmueller** [comment]
Great. If everything works well, send me a short note and I will publish version 3.0.0 to TER/Packagist.

**Comment by lochmueller** [comment]
I closed this issue. I pushed version 3.0.0 to Packagist&TER a few seconds ago.

**Comment by bmack** [comment]
🙇
