### ISSUE TITLE
composer.json and release notes mismatch wrt. PHP version

### ISSUE THREAD

**Issue by foobar13372** [lochmueller/sourceopt#73]
v4.0 changelog: "Drop PHP 7.3 support"

composer.json (master): `"php": "^7.3||^7.4||^8.0",`

Which one is correct? Can I still use it on PHP 7.3 or not?

**Comment by lochmueller** [comment]
You are right... I dropped the PHP 7.2 support and adapt the release notes: https://github.com/lochmueller/sourceopt/releases/tag/4.0.0
You can still use PHP 7.3
