### ISSUE TITLE
Sourceopt destroys XML-Sitemap & RSS feed (blog extension)

### ISSUE THREAD

**Issue by t3guards** [lochmueller/sourceopt#76]
As soon as Sourceopt is activated, no sitemap of the seo extension (seo) and also no RSS feed of the blog extension (blog) will be generated. Tested in TYPO3 .10.4.21, Sourceopt 4.0.1

**Comment by lochmueller** [comment]
Hey @cogtail 
easiest solution would be to disable the source opt extension via pageType.
Perhaps we could check the content type in the middleware https://github.com/lochmueller/sourceopt/blob/master/Classes/Middleware/CleanHtmlMiddleware.php#L49 in front of the cleanup and this should be "text/html"?! So XML is not touched anymore...

Regards,
Tim

**Comment by bavarianbytes** [comment]
Can confirm it. My solution so far:
``` 
[getTSFE().type == 1533906435]
	# disable HTML compression via ext sourceopt for sitemap
	config {
		sourceopt.enabled = 0
		svgstore.enabled = 0
	}
[end]
``` 
``` 
[getTSFE().type == 9818]
	# disable HTML compression via ext sourceopt for RSS feed
	config {
		sourceopt.enabled = 0
		svgstore.enabled = 0
	}
[end]

```

**Comment by xerc** [comment]
please check version 4.0.2
