### ISSUE TITLE
SVGStore must not apply to <picture><img src="pic.svg"></picture>

### ISSUE THREAD

**Issue by Ceremony64** [lochmueller/sourceopt#78]
The picture html construct allows the browser to select the most suitable picture based on the device specifications (e.g. orientation, resolution, etc.). It does require a single img element within it to properly function and to allow for backward compatibility as well (e.g. Internet Explorer and other trash)

However when the new svgstore feature replaces said `<img>` with a `<svg>`, it essentially breaks the <picture> element and the alternative images do not work.

More on `<picture>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

**Comment by xerc** [comment]
may you please provide examples where `<(img|source) src=".svg"` is used within `<picture>`

**Comment by Ceremony64** [comment]
Here is an example for dark using a different image when relying on the users color preference ("dark mode"):
```html
<picture>
  <source srcset="logo-dark.svg" media="(prefers-color-scheme: dark)"/>
  <img src="logo-default.svg"/>
</picture>
```

the different sources may also differ in aspect ratio, thus swapping a landscape SVG with a portrait SVG, depending on viewport size may also be useful:
```html
<picture>
  <source srcset="pic-tall.svg" media="(max-width: 800px)"/>
  <img src="pic-wide.svg"/>
</picture>
```

And finally, you can expand on the fallback option and define a hierarchy of preferred formats. first supported option gets picked in this case. however, for this example it is unrealistic that the `<img>` itself is an SVG:
```html
<picture>
  <source srcset="pic.svg" type="image/svg+xml"/>
  <source srcset="pic.png" type="image/png"/>
  <img src="pic.svg"/>
</picture>
```

**Comment by xerc** [comment]
> Here is an example for dark using a different image when relying on the users color preference ("dark mode"):

would suggest to use https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="[..]" fill="currentColor">` & @CSS via `color:`

> the different sources may also differ in aspect ratio, thus swapping a landscape SVG with a portrait SVG, depending on viewport size may also be useful:

true

**Comment by xerc** [comment]
please check version 4.0.2

**Comment by Ceremony64** [comment]
Looks good to me! Thanks!
