### ISSUE TITLE
Exception: ... SvgStoreService::addFileToSpriteArr() must be of the type array or null ...

### ISSUE THREAD

**Issue by kurtwithslc** [lochmueller/sourceopt#85]
After updating of sourceopt to version to 4.0.2 i got this error (and WEB Site is broken):

Uncaught TYPO3 Exception: Return value of HTML\Sourceopt\Service\SvgStoreService::addFileToSpriteArr() must be of the type array or null, bool returned | TypeError thrown in file /html/typo3/typo3conf/ext/sourceopt/Classes/Service/SvgStoreService.php in line 132. ...

**Comment by xerc** [comment]
it is already fix'd ; preferable use `"lochmueller/sourceopt": "dev-master"` @ `composer.json`

**Comment by lochmueller** [comment]
FIxed in current master by @xerc Will push a new version in a few minutes.

**Comment by lochmueller** [comment]
Please use version 4.0.3

**Comment by kurtwithslc** [comment]
4.0.3 runs !

thanks and merry christmas :)

Schöne Grüsse
Kurt Knote

Mühlweg 39
D-92637 Weiden
***@***.***
