### ISSUE TITLE
Problem with special Pagetype

### ISSUE THREAD

**Issue by MichiSpandl** [lochmueller/sourceopt#89]
Hello,
since Version 4 i get problems with xml or json pages (special typeNums), they are not getting rendered.
I tried to deactivate sourceopt in typoscript for this pagetypes, but still they are not getting rendered.
Any ideas what I need to do?
Best regards and thank you,
Michaela

**Comment by xerc** [comment]
please check your version >= `4.0.3` and the `Content-Type` of your xml/json requests to be not `text/html`

**Comment by MichiSpandl** [comment]
TYPO3 10.4.21, sourceopt 4.0.3 and ContentType:
```
additionalHeaders {
	10 {
		header = Content-Type:text/xml
		replace = 1
	}
}
```
or 
`application/json`

Problem still exists...

**Comment by MichiSpandl** [comment]
Ok weird, it's working now, maybe caching or something...
