### ISSUE TITLE
Php 7.3 support

### ISSUE THREAD

**Issue by helfalt** [lochmueller/sourceopt#91]
As far as see, you have skipped support for PHP 7.3 in version 4.0.3 in composer.json, but not in ext_emconf.php.

I have a composer installation using PHP 7.3 and had to downgrade to version 4.0.1 now due to a bug in 4.0.2. 

I think PHP 7.3 should be supported as it is the minimum required version for TYPO3 10 LTS.

**Comment by xerc** [comment]
please specify the "bug"

btw/ TYPO3 10.4 supports PHP 7.2 [[ref.](https://typo3.org/cms/roadmap/#legend)] which should NOT be used anymore [[ref.](https://www.php.net/supported-versions.php)]

**Comment by helfalt** [comment]
Well, I just would like to clarify whether you are still supporting PHP 7.3. There are different informations in composer.json and ext_emconf.php.
