### ISSUE TITLE
Breaks Ext:cart Ajax functionality

### ISSUE THREAD

**Issue by t3webman** [lochmueller/sourceopt#95]
If I include sourceopt in my cart test installations the 'addtocart' button does not function anymore

**Comment by lochmueller** [comment]
Hey @t3webman 

Could you add the markup with and without EXT:sourceopt that get destroyed? 
Then we can add this to tests and fix the problem.

Regards,
Tim

**Comment by Bonnography** [comment]
I had the same problem.
I use a ajax Page for a Job-Search, but if I activate Sourceopt the page is empty.
But if I set disableAllHeaderCode for the ajax page to 0 it works...

**Comment by xerc** [comment]
@Bonnography would you please provide the before and after output via `curl -s -D - -o /dev/null <URL>` ?

**Comment by lochmueller** [comment]
Hey @Bonnography 

same answer:

Could you add the markup with and without EXT:sourceopt that get destroyed (with disableAllHeaderCode)?
Then we can add this to tests and fix the problem.

Regards,
Tim

**Comment by xerc** [comment]
if `disableAllHeaderCode` there is no `<html>` not `<head/body>` => [FIX'd](https://github.com/xerc/sourceopt/commit/7a2b71b05c8b8886d2b4197c7722364bf134cde1#diff-61d99fe97ab1edbad09468dbb88bc0aaa9f64eec802a72f861d5e0bf659776d7L46-R49)

**Comment by lochmueller** [comment]
ok. Closed.

**Comment by Bonnography** [comment]
Wow that was fast ! ;D 
Works great thank you!
